# Generated by Django 2.1.5 on 2019-02-12 05:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allplans',
            new_name='Landline',
        ),
    ]
