# Generated by Django 2.1.5 on 2019-02-12 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20190212_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='landline',
            name='dateposted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
