# Generated by Django 2.1.5 on 2019-02-14 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0003_landline_dateposted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadband',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planname', models.CharField(max_length=100)),
                ('speed', models.CharField(max_length=100)),
                ('fmc', models.CharField(max_length=50)),
                ('freedata', models.CharField(max_length=100)),
                ('freeCalls', models.CharField(max_length=150)),
                ('callcharges', models.CharField(max_length=100)),
                ('securitydeosit', models.CharField(max_length=100)),
                ('addfac', models.TextField()),
                ('remark', models.TextField()),
                ('dateposted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
